config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :suisuinians
  root "welcome#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/suisuinian.rb
class Suisuinian < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/suisuinians_controller.rb
class SuisuiniansController < ApplicationController

  def index
    @suisuinian = Suisuinian.all
    @nsuisuinian= Suisuinian.new
  #  @editsuisuinian = Suisuinian.find(params[:id])
  end

  def new
    @suisuinian=Suisuinian.new
  end

  def create
    @suisuinian= Suisuinian.new(suisuinian_params)
    @suisuinian.save

    redirect_to suisuinians_path
  end

  def edit
#    @suisuinian=Suisuinian.find(params[:id])
  end

  def update
    @suisuinian=Suisuinian.find(params[:id])
    @suisuinian.update(suisuinian_params)

    redirect_to suisuinians_path
  end

  def destroy
    @suisuinian=Suisuinian.find(params[:id])
    @suisuinian.destroy

    redirect_to suisuinians_path
  end

  def show
    @suisuinian=Suisuinian.find(params[:id])
  end


  private

  def suisuinian_params
    params.require(:suisuinian).permit(:title,:description)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/suisuinians_helper.rb
module SuisuiniansHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Quora
        <br>Design by
        <a href="#" target=_new>朱连杰</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><%=content_tag(:span, "", :class => "fa fa-calendar")%></a>
            <a class="navbar-brand" href="/suisuinians">碎碎念</a>
            <a class="navbar-brand" href="/">解法</a>
            <a class="navbar-brand" href="#">复盘</a>
            <a class="navbar-brand" href="/">系统化</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to("搜索","#",class: "btn btn-default pull-right" ) %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/common/_redit.html.erb
<div class="modal fade" id="edit-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
       <h2>编辑碎碎念</h2>
       <%= simple_form_for @editsuisuinian do |f| %>
         <div class="form-inputs">
           <%= f.input :title, input_html: { class: "form-control"} %>
           <%= f.input :description, input_html: { class: "form-control"} %>
         </div>
         <div class="form-actions">
           <%= link_to("取消",suisuinians_path) %>
           <%= f.button :submit, "更新" %>
         </div>
       <% end %>
 </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quora</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>

  </body>
</html>

app/views/suisuinians/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增碎碎念</h2>

    <hr>
    <%= form_for @suisuinian do |f| %>

    标题
    <%= f.text_field :title %>
    <br>
    叙述
    <br>
    <%= f.text_area :description %>
    <br>

    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %>

</div>

app/views/suisuinians/index.html.erb
<div class="col-md-12">
  <div class= "btn btn-default pull-right">
<a  data-toggle="modal" data-target="#nsuisuinian-modal">今日碎碎念</a>
  <!-- <%= link_to("今日碎碎念", new_suisuinian_path,calss:"btn btn-primary pull-right") %> -->
  </div>







  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>标   题</td>
        <td>描   述</td>
      </tr>
    </thead>
    <tbody>
      <% @suisuinian.each do |suisuinian| %>
        <tr>
          <td>#</td>
          <td><%= link_to(suisuinian.title, suisuinian_path(suisuinian)) %></td>
          <td><%= suisuinian.description %></td>
          <td>
            <a  data-toggle="modal" data-target="#edit-modal"><%= content_tag(:span,"", :class=> "fa fa-pencil") %> </a>

        <!--  <%= link_to(content_tag(:span, "", :class => "fa fa-pencil"), edit_suisuinian_path(suisuinian), class: "btn btn-sm btn-default")%> -->


            <%= link_to(content_tag(:span, "", :class => "fa fa-trash-o"), suisuinian_path(suisuinian),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>

        <div class="modal fade" id="edit-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
          <div class="modal-dialog" role="document">
            <div class="loginmodal-container">
               <h2>编辑碎碎念</h2>
               <%= simple_form_for suisuinian do |f| %>
                 <div class="form-inputs">
                   <%= f.input :title, input_html: { class: "form-control"} %>
                   <%= f.input :description, input_html: { class: "form-control"} %>
                 </div>
                 <div class="form-actions">
                   <%= link_to("取消",suisuinians_path) %>
                   <%= f.button :submit, "更新" %>
                 </div>
               <% end %>
         </div>
          </div>
        </div>


      <% end %>
    </tbody>
  </table>








  <div class="modal fade" id="nsuisuinian-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" role="document">
      <div class="loginmodal-container">
         <h2>新增碎碎念</h2>
         <%= simple_form_for @nsuisuinian do |f| %>
           <div class="form-inputs">
             <%= f.input :title, input_html: { class: "form-control"} %>
             <%= f.input :description, input_html: { class: "form-control"} %>
           </div>
           <div class="form-actions">
             <%= link_to("取消",suisuinians_path) %>
             <%= f.button :submit, "提交" %>
           </div>
         <% end %>
      </div>
    </div>
  </div>





</div>

app/views/suisuinians/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <a  href="#" data-toggle="modal" data-target="#newsuisuinian-modal"> 新增碎碎念</a>



</div>

app/views/suisuinians/show.html.erb
<div class="col-md-12">
  <div class="suisuinian">
    <%= link_to("Edit", edit_suisuinian_path(@suisuinian), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @suisuinian.title %></h2>
  <p><%= @suisuinian.description %></p>
</div>

app/views/welcome/index.html.erb
<h3> 欢迎使用<em>Quora</em></h3>